# PANDAS GİRİŞ

 ## Veriyi topladıktan sonra veriyi analize uygun hale getirmek, veri analizi için oldukça önemlidir. Veri bilimcilerinin 
 ## en fazla zamanlarını alan aşama veri ön işleme ve veri temizlemedir. Pandas kütüphanesi ile veri organize edilerek 
 ## analizler daha kolay ve hızlı yapılır. Pandas Python’ın en önemli kütüphanelerinden biridir.

# Pandas Seri Oluşturmak

In [1]:
import pandas as pd

In [3]:
seri = pd.Series([1,2,3,4,5])
seri

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
type(seri)

pandas.core.series.Series

In [10]:
seri.axes #indeks rangeini ifade eder

[RangeIndex(start=0, stop=5, step=1)]

In [11]:
seri.dtype # Seri içerisindeki elemanlarının tipini gösterir

dtype('int64')

In [12]:
seri.size #Serinin eleman sayısını verir

5

In [13]:
seri.ndim #Serinin Boyutunu verir

1

In [14]:
seri.values # Seri içersindeki değerlere array cinsinden erişmek istersem

array([1, 2, 3, 4, 5])

In [16]:
seri.head(3) # içerisine yazdığım değer kadarlık kısmını bana gösteriyor

0    1
1    2
2    3
dtype: int64

In [17]:
seri.tail(3) # headin tam tersi sondan yazzdığımız sayı kadarını gösteriri

2    3
3    4
4    5
dtype: int64

# İndeks İsimlendirme 

In [18]:
pd.Series([99,3,1,5,21])

0    99
1     3
2     1
3     5
4    21
dtype: int64

In [21]:
## İndex 0 dan başlayacak şekilde değilde a b c d e şeklinde veridik

In [22]:
pd.Series([99,3,1,5,21], index = ["a","b","c","d","e"])

a    99
b     3
c     1
d     5
e    21
dtype: int64

In [23]:
seri = pd.Series([99,3,1,5,21], index = ["a","b","c","d","e"])

In [24]:
seri["a"]

np.int64(99)

In [26]:
seri["a":"d"] # a dan d ye kadar git

a    99
b     3
c     1
d     5
dtype: int64

## Sozluk Uzerinden Liste Olusturmak

In [44]:
sozluk = pd.Series({"Interface" : {"Arayuz":"Etkileşim"},
                    "ndim":"Boyut sorgulama",
                    "size":"Eleman sayısı sorgusu"})
seri = pd.Series(sozluk)
seri

Interface    {'Arayuz': 'Etkileşim'}
ndim                 Boyut sorgulama
size           Eleman sayısı sorgusu
dtype: object

In [46]:
seri["Interface"]["Arayuz"]

'Etkileşim'

## İki Tane Seriyi Birleştirerek Bir Seri oluşturmak

In [47]:
sozluk = pd.Series({"Interface" : {"Arayuz":"Etkileşim"},
                    "ndim":"Boyut sorgulama",
                    "size":"Eleman sayısı sorgusu"})
seri_sozluk = pd.Series(sozluk)
seri_sozluk

Interface    {'Arayuz': 'Etkileşim'}
ndim                 Boyut sorgulama
size           Eleman sayısı sorgusu
dtype: object

In [48]:
seri = pd.Series([19,20,30,12], index = ["a","b","c","d"])
seri

a    19
b    20
c    30
d    12
dtype: int64

In [50]:
pd.concat([seri_sozluk,seri])

Interface    {'Arayuz': 'Etkileşim'}
ndim                 Boyut sorgulama
size           Eleman sayısı sorgusu
a                                 19
b                                 20
c                                 30
d                                 12
dtype: object

# ELEMAN İŞLEMLERİ 

In [51]:
import numpy as np
a = np.array([21,23,43,46,75])
seri = pd.Series(a)
seri

0    21
1    23
2    43
3    46
4    75
dtype: int64

In [52]:
seri[0]

np.int64(21)

In [54]:
seri[3:5]

3    46
4    75
dtype: int64

In [84]:
seri = pd.Series([120,200,150,99], index = ["reg","loj","cart","rf"])
seri

reg     120
loj     200
cart    150
rf       99
dtype: int64

In [57]:
seri.index # Sadece index değerlerini ekrana yazdıracak

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [59]:
list(seri.items()) # key and value liste şekilnde görmemizi sağlar


[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [67]:
list(seri.values) # liste şekilnde sadece values görmüş olduk
seri.values # Array şeklinde sadece values görceğiz

array([121, 200, 150,  99])

In [72]:
list(seri.keys()) # Liste şeklinde sadece keyleri görmüş olduk 
seri.keys() #  Array şeklinde sadece keys göreceğiz

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

## Eleman Sorgulama İşlemleri

In [81]:
"reg" in seri

True

In [82]:
"a" in seri

False

In [87]:
seri["reg"]

np.int64(120)

## Fancy Yönetimi

In [85]:
seri[["rf","reg"]]

rf      99
reg    120
dtype: int64

In [88]:
seri["reg"]

np.int64(120)

In [90]:
seri["reg"] = 1330
seri["reg"]

np.int64(1330)

In [176]:
seri["reg":"rf"]

reg     1330
loj      200
cart     150
rf        99
dtype: int64

# Pandasta DataFrame(Veri Çerçevesi Deposu) Oluşturma 

In [92]:
import pandas as pd

In [96]:
l = list([1,2,39,67,90])
l

[1, 2, 39, 67, 90]

In [99]:
pd.DataFrame(l, columns = ["Degisken_ismi"])

Degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [102]:
import numpy as np
m = np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
pd.DataFrame(m, columns = ["Var1","Var2","Var3"])

Var1  Var2  Var3
0     1     2     3
1     4     5     6
2     7     8     9

## df isimlendirme 

In [107]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
df = pd.DataFrame(a, columns=["Var1","Var2","Var3"])
df.head(2)

Var1  Var2  Var3
0     1     2     3
1     4     5     6

In [112]:
df.columns

Index(['Var1', 'Var2', 'Var3'], dtype='object')

In [114]:
type(df)

pandas.core.frame.DataFrame

In [115]:
df.empty

False

In [117]:
df.dtypes

Var1    int64
Var2    int64
Var3    int64
dtype: object

In [118]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['Var1', 'Var2', 'Var3'], dtype='object')]

In [119]:
df.shape

(3, 3)

In [120]:
df.size

9

In [121]:
df.ndim

2

In [125]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
type(df.values)

numpy.ndarray

In [127]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [129]:
pd.DataFrame(a, columns = ["Values1"])

Values1
0        1
1        2
2        3
3        4
4        5

# Pandas Data Frame(Veri Çerçevesi) Elaman İşlemleri

In [211]:
import numpy as np
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [212]:
s1

array([6, 2, 3, 3, 9], dtype=int32)

In [213]:
s2

array([3, 8, 1, 5, 0], dtype=int32)

In [214]:
s3

array([1, 8, 0, 6, 5], dtype=int32)

In [215]:
dictionary = {"var1" : s1 , "var2" : s2 , "var3" : s3}
dictionary

{'var1': array([6, 2, 3, 3, 9], dtype=int32),
 'var2': array([3, 8, 1, 5, 0], dtype=int32),
 'var3': array([1, 8, 0, 6, 5], dtype=int32)}

In [216]:
df = pd.DataFrame(dictionary, index = ["a","b","c","d","e"] )
df

var1  var2  var3
a     6     3     1
b     2     8     8
c     3     1     0
d     3     5     6
e     9     0     5

In [217]:
df[0:2]

var1  var2  var3
a     6     3     1
b     2     8     8

In [218]:
df["var1"]

a    6
b    2
c    3
d    3
e    9
Name: var1, dtype: int32

In [219]:
df[["var1","var2"]]

var1  var2
a     6     3
b     2     8
c     3     1
d     3     5
e     9     0

In [220]:
df["a":"c"]

var1  var2  var3
a     6     3     1
b     2     8     8
c     3     1     0

## SİLEME İŞLEMİ

In [221]:
df.drop("b", axis = 0)

var1  var2  var3
a     6     3     1
c     3     1     0
d     3     5     6
e     9     0     5

In [223]:
df.drop("b", axis = 0, inplace = True)

In [224]:
df

var1  var2  var3
a     6     3     1
c     3     1     0
d     3     5     6
e     9     0     5

## FANCY YÖNTEMİ İLE BİRDEN FAZLA DEĞER SİLME 

In [233]:
silinecekler = ["a","d"]

In [234]:
df.drop(silinecekler, axis = 0, inplace = True)

In [235]:
df

var1  var2  var3
c     3     1     0
e     9     0     5

## Değişkenler İçin

In [237]:
l = ["var1","var4","var3"]

In [238]:
for i in l:
    print(i in df)

True
False
True


In [240]:
df["var4"] = df["var1"] / df["var2"]

In [241]:
df

var1  var2  var3  var4
c     3     1     0   3.0
e     9     0     5   inf

## Değişken Silmek 

In [247]:
df.drop("var4", axis = 1)

var1  var2  var3
c     3     1     0
e     9     0     5

In [248]:
df

var1  var2  var3  var4
c     3     1     0   3.0
e     9     0     5   inf

In [249]:
df.drop("var4", axis = 1, inplace = True)

In [250]:
df

var1  var2  var3
c     3     1     0
e     9     0     5

In [252]:
silinecekler = ["var1","var2"]
df.drop(silinecekler, axis = 1, inplace = True)

In [253]:
df

var3
c     0
e     5

# Gözlem Ve Değişken Seçimi: loc & iloc

In [2]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0     3     9    24
1    16    18    11
2     8     7    19
3    20    10    19
4    16    19    21
5     6    11    11
6    16    14    11
7    21     1    12
8     8     1    12
9     3     9    18

## loc: Tanımlandığı şekil ile seçim yapmak için kullanılır

In [3]:
df.loc[0:3]

var1  var2  var3
0     3     9    24
1    16    18    11
2     8     7    19
3    20    10    19

In [21]:
df

var1  var2  var3
0    12    16    11
1    10     5    10
2    20     8    17
3    17    14    17
4    11    10    28
5    11    24    16
6    13    29    12
7     8    13    19
8     8    23    17
9    23    29    22

In [22]:
df.loc[0:2,"var3"] 

0    11
1    10
2    17
Name: var3, dtype: int32

In [25]:
df.iloc[0:3]["var3"]

0    11
1    10
2    17
Name: var3, dtype: int32

## iloc: Alışık olduğumuz indeskleme mantığı ile seçim yapar

In [4]:
df.iloc[0:3]

var1  var2  var3
0     3     9    24
1    16    18    11
2     8     7    19

In [10]:
df.iloc[0,0] ## ÖNEMLİ: virgülden öncesi satır sonrası sütunu ifade eder

np.int32(3)

In [6]:
df.iloc[:3,2]

0    24
1    11
2    19
Name: var3, dtype: int32

In [11]:
df.iloc[:3]["var3"]

0    24
1    11
2    19
Name: var3, dtype: int32

# Koşullu Eleman İşlemleri

In [1]:
import numpy as np 
import pandas as pd 
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m , columns = ["var1","var2","var3"])
df

var1  var2  var3
0    12    16    11
1    10     5    10
2    20     8    17
3    17    14    17
4    11    10    28
5    11    24    16
6    13    29    12
7     8    13    19
8     8    23    17
9    23    29    22

In [8]:
df["var1"]

0    12
1    10
2    20
3    17
4    11
5    11
6    13
7     8
8     8
9    23
Name: var1, dtype: int32

In [9]:
df.var1

0    12
1    10
2    20
3    17
4    11
5    11
6    13
7     8
8     8
9    23
Name: var1, dtype: int32

In [17]:
df[(df.var1 > 15)] # Koşullu işlemlerin yapımı

var1  var2  var3
2    20     8    17
3    17    14    17

In [20]:
df.loc[(df.var1 > 15), ["var1", "var2"]]

var1  var2
2    20     8
3    17    14
9    23    29

In [29]:
df[(df.var1 > 15)][["var1","var2"]]

var1  var2
2    20     8
3    17    14
9    23    29

# Basit Birleştirme (Join) İşlemleri:

In [31]:
import numpy as np 
import pandas as pd 
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m , columns = ["var1","var2","var3"])
df1

var1  var2  var3
0    16    14    10
1    15    18    15
2     1     1    19
3    27    25    11
4    18    21     2

In [33]:
df2 = df1 + 99
df2

var1  var2  var3
0   115   113   109
1   114   117   114
2   100   100   118
3   126   124   110
4   117   120   101

In [34]:
pd.concat([df1,df2 # Birleştirme işlemi gerçekleşti fakat indexleme işleminde bir sıkıntı çıktı 

var1  var2  var3
0    16    14    10
1    15    18    15
2     1     1    19
3    27    25    11
4    18    21     2
0   115   113   109
1   114   117   114
2   100   100   118
3   126   124   110
4   117   120   101

In [41]:
?pd.concat # Düzeltme İşlemini Araştırıp bulduk 

Signature:
pd.concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
  

In [43]:
pd.concat([df1,df2], ignore_index=True) # düzenlenmiş hali bu şekilde olacaktır

var1  var2  var3
0    16    14    10
1    15    18    15
2     1     1    19
3    27    25    11
4    18    21     2
5   115   113   109
6   114   117   114
7   100   100   118
8   126   124   110
9   117   120   101

In [45]:
?df.columns

Type:        Index
String form: Index(['var1', 'var2', 'var3'], dtype='object')
Length:      3
File:        c:\anaconda3\lib\site-packages\pandas\core\indexes\base.py
Docstring:  
Immutable sequence used for indexing and alignment.

The basic object storing axis labels for all pandas objects.

.. versionchanged:: 2.0.0

   Index can hold all numpy numeric dtypes (except float16). Previously only
   int64/uint64/float64 dtypes were accepted.

Parameters
----------
data : array-like (1-dimensional)
dtype : str, numpy.dtype, or ExtensionDtype, optional
    Data type for the output Index. If not specified, this will be
    inferred from `data`.
    See the :ref:`user guide <basics.dtypes>` for more usages.
copy : bool, default False
    Copy input data.
name : object
    Name to be stored in the index.
tupleize_cols : bool (default: True)
    When True, attempt to create a MultiIndex if possible.

See Also
--------
RangeIndex : Index implementing a monotonic integer range.
CategoricalIndex

In [48]:
df1.columns = ["deg1","deg2","deg3"]
df1.columns

Index(['deg1', 'deg2', 'deg3'], dtype='object')

In [49]:
df1

deg1  deg2  deg3
0    16    14    10
1    15    18    15
2     1     1    19
3    27    25    11
4    18    21     2

In [50]:
df2

var1  var2  var3
0   115   113   109
1   114   117   114
2   100   100   118
3   126   124   110
4   117   120   101

In [52]:
pd.concat([df1,df2]) # İsimlerin değiştiği zaman çıktımız baya bir problemli olmuş oldu

deg1  deg2  deg3   var1   var2   var3
0  16.0  14.0  10.0    NaN    NaN    NaN
1  15.0  18.0  15.0    NaN    NaN    NaN
2   1.0   1.0  19.0    NaN    NaN    NaN
3  27.0  25.0  11.0    NaN    NaN    NaN
4  18.0  21.0   2.0    NaN    NaN    NaN
0   NaN   NaN   NaN  115.0  113.0  109.0
1   NaN   NaN   NaN  114.0  117.0  114.0
2   NaN   NaN   NaN  100.0  100.0  118.0
3   NaN   NaN   NaN  126.0  124.0  110.0
4   NaN   NaN   NaN  117.0  120.0  101.0

# İleri Seviye Birleştirme İşlemleri:

## Birebir Birleştirme İşlemi 

In [55]:
import pandas as pd

In [56]:
df1 = pd.DataFrame({"Calisanlar" : ["Ali","Veli","Ayse","Fatma"],
                    "Grup": ["Muhasebe","Muhendislik","Muhendislik","İK"]})
df1

Calisanlar         Grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [58]:
df2 = pd.DataFrame({"Calisanlar" : ["Ayse","Ali","Veli","Fatma"],
                    "ilk_giris": [2010,2009,2014,2019]})
df2

Calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [62]:
pd.merge(df1,df2) # En sık kullanılan birleştirme işlemidir birleştirme işlemini kendisi hallediyor

Calisanlar         Grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [64]:
pd.merge(df1,df2, on = "Calisanlar") # İstediğimiz bir başlığa görede birleştirme işlemi yapabiliyor

Calisanlar         Grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

## Çoktan Teke Birleştirme işlemi

In [66]:
df3 = pd.merge(df1,df2) 
df3

Calisanlar         Grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [68]:
df4 = pd.DataFrame({"Grup": ["Muhasebe","Muhendislik","İK"],
                    "mudur" : ["Caner","Mustafa","Berkcan"]})
df4

Grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [71]:
df5 = pd.merge(df3,df4)
df5

Calisanlar         Grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

## Çoktan Çoka Birleştirme İşlemi

In [76]:
df6 = pd.DataFrame({"Grup": ["Muhasebe","Muhasebe","Muhendislik","Muhendislik","İK","İK"],
                    "yetenekler" : ["matematik","excel","kodlama","linux","excel","yoneyim"]})
df6

Grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yoneyim

In [77]:
pd.merge(df5,df6,  on = "Grup")

Calisanlar         Grup  ilk_giris    mudur yetenekler
0        Ali     Muhasebe       2009    Caner  matematik
1        Ali     Muhasebe       2009    Caner      excel
2       Veli  Muhendislik       2014  Mustafa    kodlama
3       Veli  Muhendislik       2014  Mustafa      linux
4       Ayse  Muhendislik       2010  Mustafa    kodlama
5       Ayse  Muhendislik       2010  Mustafa      linux
6      Fatma           İK       2019  Berkcan      excel
7      Fatma           İK       2019  Berkcan    yoneyim

# Toplulaştırma Ve Gruplaştırma (Aggregation & Grouping)

# Basit Toplulaştırma Fonksiyonları
* count() # sayma
* last() # son değer
* mean() # ortalama
* median() # Medyan(Ortadaki değer)
* min() # En küçük değer
* std() # standart sapma
* var() # verilerin ortalamaya göre değişkenliğini ölçer
* sum() # Toplam

In [79]:
veri = {"ogrenci_adi": ["Mehmet","Busra","Adem","Sura","Gorkem","Aleyna"],
        "Not" : [70,100,80,75,90,92]}
df = pd.DataFrame(veri)
df

ogrenci_adi  Not
0      Mehmet   70
1       Busra  100
2        Adem   80
3        Sura   75
4      Gorkem   90
5      Aleyna   92

In [81]:
df["Not"].count() # Kaç adet not verisi olduğunu gösteriri

np.int64(6)

In [84]:
df["Not"].iloc[0] # Girilen ilk veriyi gösteriri

np.int64(70)

In [85]:
df["Not"].iloc[-1] # Girilen son veriyi gösterir

np.int64(92)

In [87]:
df["Not"].mean() # Girilen not verilerinin ortalamasını alır

np.float64(84.5)

In [89]:
df["Not"].median() # Girilen verilerden ortanca olan değeri bulur

85.0

In [94]:
df["Not"].min() # Girilen verilerden en düşük değere sahip olan veriyi bulur

70

In [93]:
df["Not"].max() # Girilen verilerden en yüksek değer sahip olan veriyi bulur

100

In [98]:
df["Not"].std() # Verilerin ne kadar dağıldığını gösterir. Yani veriler ortalamadan ne kadar uzak olduğunu gösterir.

11.379806676741042

In [99]:
df["Not"].var() # Verilerin ortalamaya göre değişkenliğini ölçer. std()'nin karesidir.

129.5

In [100]:
df["Not"].sum() # Verilerin toplamını verir.

np.int64(507)

In [102]:
import seaborn as sns

In [105]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [109]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [110]:
df.shape

(1035, 6)

In [112]:
df.mean(numeric_only=True)

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [113]:
df["mass"].mean(numeric_only=True)

np.float64(2.6381605847953216)

In [116]:
df["orbital_period"].std()

26014.72830406252

In [117]:
df["year"].min()

1989

In [121]:
df.describe() # Veri setindeki tüm verilerin istatistiksel değerlini oluşturan bir tablo

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [122]:
df.dropna().describe().T # Eksik değerleri silince ki halini gösterdi

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

# Gruplama İşlemleri:

In [15]:
import pandas as pd
df = pd.DataFrame({'Group' : ['A', 'B', 'C', 'A', 'B', 'C'],
                   'Data': [10,11,52,23,43,55]})
df

Group  Data
0     A    10
1     B    11
2     C    52
3     A    23
4     B    43
5     C    55

In [17]:
df.groupby("Group") # Şuan listede bulunan A B C sınıflarına ait verileri aldı 
# örneğin; A ---> 10 , 23 / B ---> 11 , 43 / C ---> 52 , 55 gibi 
# Fakat ne yapacağını bilmiyor geçen derste öğrendiğimiz metotlarla ne yapması gerektiğini anlatmamız lazım

In [18]:
df.groupby("Group").mean() # Grupların ortalamasını al demek

Data
Group      
A      16.5
B      27.0
C      53.5

In [19]:
df.groupby("Group").sum()

Data
Group      
A        33
B        54
C       107

In [26]:
import seaborn as sns
df = sns.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [38]:
df.groupby("method")

In [42]:
df.groupby("method")[["orbital_period","mass","distance"]].mean()

orbital_period      mass     distance
method                                                              
Astrometry                         631.180000       NaN    17.875000
Eclipse Timing Variations         4751.644444  5.125000   315.360000
Imaging                         118247.737500       NaN    67.715937
Microlensing                      3153.571429       NaN  4144.000000
Orbital Brightness Modulation        0.709307       NaN  1180.000000
Pulsar Timing                     7343.021201       NaN  1200.000000
Pulsation Timing Variations       1170.000000       NaN          NaN
Radial Velocity                    823.354680  2.630699    51.600208
Transit                             21.102073  1.470000   599.298080
Transit Timing Variations           79.783500       NaN  1104.333333

In [43]:
df.groupby("method")["mass"].describe()

count      mean       std     min      25%  \
method                                                                      
Astrometry                       0.0       NaN       NaN     NaN      NaN   
Eclipse Timing Variations        2.0  5.125000  1.308148  4.2000  4.66250   
Imaging                          0.0       NaN       NaN     NaN      NaN   
Microlensing                     0.0       NaN       NaN     NaN      NaN   
Orbital Brightness Modulation    0.0       NaN       NaN     NaN      NaN   
Pulsar Timing                    0.0       NaN       NaN     NaN      NaN   
Pulsation Timing Variations      0.0       NaN       NaN     NaN      NaN   
Radial Velocity                510.0  2.630699  3.825883  0.0036  0.22525   
Transit                          1.0  1.470000       NaN  1.4700  1.47000   
Transit Timing Variations        0.0       NaN       NaN     NaN      NaN   

                                 50%     75%    max  
method                                               
Astrometry                       NaN     NaN    NaN  
Eclipse Timing Variations      5.125  5.5875   6.05  
Imaging                          NaN     NaN    NaN  
Microlensing                     NaN     NaN    NaN  
Orbital Brightness Modulation    NaN     NaN    NaN  
Pulsar Timing                    NaN     NaN    NaN  
Pulsation Timing Variations      NaN     NaN    NaN  
Radial Velocity                1.260  3.0000  25.00  
Transit                        1.470  1.4700   1.47  
Transit Timing Variations        NaN     NaN    NaN

# İleri Toplulaştırma Yöntemi(Aggregate, filter, transform, apply)

In [13]:
import pandas as pd
import numpy as np
df = pd.DataFrame({"groups" : ["A","B","C","A","B","C"],
                   "variable1" : [10,23,33,22,11,99],
                   "variable2" : [100,253,333,262,111,969]},
                     columns = ["groups","variable1","variable2"])
df

groups  variable1  variable2
0      A         10        100
1      B         23        253
2      C         33        333
3      A         22        262
4      B         11        111
5      C         99        969

## Aggregate

In [14]:
df.groupby("groups")

In [15]:
df.groupby("groups").mean() # mean fonksiyonun yanında bir çok fonksiyon çalıştırmak istersek 
# kullanacağımzı yapı aggregate yapsısı

variable1  variable2
groups                      
A            16.0      181.0
B            17.0      182.0
C            66.0      651.0

In [17]:
df.groupby("groups").aggregate(["min", "median", "max"])

variable1            variable2            
             min median max       min median  max
groups                                           
A             10   16.0  22       100  181.0  262
B             11   17.0  23       111  182.0  253
C             33   66.0  99       333  651.0  969

In [20]:
df.groupby("groups").aggregate({"variable1" : ["min","median","max"],
                                "variable2" : ["mean","sum","std"]})

variable1            variable2                  
             min median max      mean   sum         std
groups                                                 
A             10   16.0  22     181.0   362  114.551299
B             11   17.0  23     182.0   364  100.409163
C             33   66.0  99     651.0  1302  449.719913

# Filter Pandasta elimizde olamyan ve kendimize özgü fonksiyonları filter olarak ele alma

In [21]:
import pandas as pd
import numpy as np
df = pd.DataFrame({"groups" : ["A","B","C","A","B","C"],
                   "variable1" : [10,23,33,22,11,99],
                   "variable2" : [100,253,333,262,111,969]},
                     columns = ["groups","variable1","variable2"])
df

groups  variable1  variable2
0      A         10        100
1      B         23        253
2      C         33        333
3      A         22        262
4      B         11        111
5      C         99        969

In [22]:
def filter_func(x):
    return x["variable1"].std() > 9

In [24]:
df.groupby("groups").std()

variable1   variable2
groups                       
A        8.485281  114.551299
B        8.485281  100.409163
C       46.669048  449.719913

In [23]:
df.groupby("groups").filter(filter_func)

groups  variable1  variable2
2      C         33        333
5      C         99        969

## Transform (Dönüşüm İşlemi)

In [1]:
import pandas as pd 
df = pd.DataFrame({"groups": ["A","B","C","A","B","C"],
                   "variable1" : [10,23,33,22,11,99],
                   "variable2" : [100,253,333,262,111,969]})
df

groups  variable1  variable2
0      A         10        100
1      B         23        253
2      C         33        333
3      A         22        262
4      B         11        111
5      C         99        969

In [35]:
df_a = df.iloc[:,1:3]
df_a

variable1  variable2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [42]:
df_a.transform(lambda x: (x - x.mean()) / x.std())

variable1  variable2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

## Apply()

In [52]:
import pandas as pd 
import numpy as np
df = pd.DataFrame({"groups": ["A","B","C","A","B","C"],
                   "variable1" : [10,23,33,22,11,99],
                   "variable2" : [100,253,333,262,111,969]})
df

groups  variable1  variable2
0      A         10        100
1      B         23        253
2      C         33        333
3      A         22        262
4      B         11        111
5      C         99        969

In [53]:
df.apply("sum") # Ya Da  df.apply(np.sum)

groups       ABCABC
variable1       198
variable2      2028
dtype: object

In [54]:
def function(x):
    return ((x-x.mean())/x.std())
df.groupby("groups").apply(function)

variable1  variable2
groups                        
A      0  -0.707107  -0.707107
       3   0.707107   0.707107
B      1   0.707107   0.707107
       4  -0.707107  -0.707107
C      2  -0.707107  -0.707107
       5   0.707107   0.707107

# Pivot Tablolar (Pivots Table)

In [57]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic.head()


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [63]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [70]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

C:\Users\Mehmet Ersolak\AppData\Local\Temp\ipykernel_10312\2203689429.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()


survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [71]:
titanic.pivot_table("survived", index = "class" ,  columns = "sex")

C:\Users\Mehmet Ersolak\AppData\Local\Temp\ipykernel_10312\1954185734.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table("survived", index = "class" ,  columns = "sex")


sex       female      male
class                     
First   0.968085  0.368852
Second  0.921053  0.157407
Third   0.500000  0.135447

In [72]:
age = pd.cut(titanic['age'], [0,18,90])
age.head(9)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [74]:
titanic.pivot_table("survived", ["sex", age], "class")

C:\Users\Mehmet Ersolak\AppData\Local\Temp\ipykernel_10312\2319210369.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table("survived", ["sex", age], "class")


class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

# Dış Kaynaklı Veri Okuma 

In [75]:
import pandas as pd

## Dış kaynaklı bir csv dosyasının okunması 

In [77]:
pd.read_csv("reading_data/ornekcsv.csv", sep = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [78]:
pd.read_csv("reading_data/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [82]:
df = pd.read_excel("reading_data/ornekx.xlsx")
df

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [83]:
type(df)

pandas.core.frame.DataFrame

In [86]:
df.columns= ("A","B","C")
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [89]:
tips = pd.read_csv("reading_data/Data_tips.txt")
tips.head(15)

total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2

# Problem Çözme Döküman Okuma Kültürü

## stackoverflow unutmaaaa

## Reading  Documentation
* Pandas documentation
* Numpy documentation