# Neden NumPy?

## Bir çok konuda bize işlem kolaylığı sağlar ve zamandan tasarruf etmemizi sağlıyor
## Vektörel işlemleri daha kolay bir şekilde yapmamızı sağlar

In [11]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

a * b 

array([ 2,  6, 12, 20])

# NumPy Array`i Oluşturmak

In [14]:
import numpy as np # numpy kütüphanesini np kısaltması ile ekleme işlemi

## 1.Yöntem:

In [17]:
a = np.array([1,2,3,4,5])

In [18]:
type(a)

numpy.ndarray

## İçerisinde tek bir veri tipi tutar

In [20]:
np.array([13.2, 1, 4, 32.3])

array([13.2,  1. ,  4. , 32.3])

## Gördüğünüz Gibi int veri türünde girdiğimiz değerler float veri türüne dönüştürüldü

In [24]:
np.array([3.14, 4, 1, 32.3], dtype = "int")

array([ 3,  4,  1, 32])

## Gördüğünüz Üzere numpy arraylarinin veri türlerini değiştirme şansımız var şimdi işe hepsini int veri tipinde tutuyor

# Sıfırdan Array Oluşturmak

In [25]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# np.full((Kaça Kaçlık Bir Dizi İstiyoruz), dizinin elemanları ne olsun, tipni belirleme)

In [27]:
np.full((3,5), 3, dtype = int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [28]:
# ÇOOK ÖMELİ 
np.arange(0, 31, 3) # sıfırdan 31 e kadar 3 er 3 er artacak bir düz dizi

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [30]:
np.linspace(0, 1, 10) # Sıfır İle bir arasında 10 tane sayı yaz

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [32]:
# ÇOOK ÖMELİ
np.random.normal(10, 4, (3,4))
# rastgele oluşacak fakat ortalamasını ve standart sapmasını bizim belirlediğimiz bir matris oluşturduk

array([[10.65397823,  8.8452057 ,  5.43537922,  5.37231968],
       [12.38026644,  7.22417786, 10.8138435 ,  8.56464627],
       [ 8.79395698,  9.86452947,  8.14371385, 10.14514015]])

In [33]:
# ÇOOK ÖMELİ
np.random.randint(0, 10, (3,3))
# üç çarpı üç ve 0 dan 10 kadar değer alabilcek yerleri rastgele olan bir matris üretme işlemi

array([[2, 3, 6],
       [6, 2, 7],
       [4, 0, 7]], dtype=int32)

# NumPy Array Özellikleri

* ndim: boyut
* shape: boyut bilgisi
* size: toplam eleman sayisi
* dtype: array veri tipi

In [34]:
import numpy as np

In [35]:
np.random.randint(10, size = 10)

array([2, 0, 8, 3, 4, 6, 1, 2, 5, 9], dtype=int32)

In [36]:
a = np.random.randint(10, size = 10)

In [37]:
a.ndim

1

In [38]:
a.shape

(10,)

In [39]:
a.size

10

In [40]:
a.dtype

dtype('int32')

In [49]:
a = np.random.randint(0, 10, (3,3))

In [50]:
a.ndim

2

In [51]:
a.shape

(3, 3)

In [52]:
a.size

9

In [53]:
a.dtype

dtype('int32')

# Yeniden Şekillendirme (Reshaping)


## Bazen çıktılar sonucu olaşan 1 boyutlu matrisleri 2 boyutlu hale getirmek lazım 
## bazende iki ya da çok  boyutlu dizileri tek boyuta ndirgemek lazım 
## bundan dolayı yeniden şekillendirme işlemini kullanmamız gerekecek

In [54]:
import numpy as np

In [55]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(1,10).reshape((3,3)) # tek boyutlu diziyi 2 boyutlu matrise dönüştürdük

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
a = np.arange(1,10)

In [64]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a.ndim

1

In [66]:
b = a.reshape((1,9))

In [67]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [68]:
b.ndim

2

# Array Birlestirme (Concatenation)

In [69]:
import numpy as np

In [71]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [72]:
z = np.concatenate([x,y])

In [74]:
z # x ve y dizilerini concatenate fonksiyonu yardımıyla birleştirdik

array([1, 2, 3, 4, 5, 6])

In [75]:
t = np.array([7,8,9])

In [77]:
np.concatenate([z,t])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## İki Boyutlu Matrisler İçin Birleştirme İşlemi

In [88]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[7,8,9],
              [10,11,12]])
c = np.concatenate([a,b])

In [89]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
## (axis = 0 Satır Bazında Birleştirme)Satır Bazında Belirtilmiş Bir Şekilde Çıktı Aldık
## (axis = 1 Sütun Bazında Birleştirme)Sütun Bazında Belirtilmiş Bir Şekilde Nasıl Çıktı Alcağız

In [96]:
c = np.concatenate([a,b], axis = 0 )
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [97]:
c = np.concatenate([a,b], axis = 0)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Arraylerde Ayırma İşlemi (Spliting)

In [98]:
import numpy as np

In [105]:
x = np.array([1,2,3,99,99,3,2,1])

In [104]:
np.split(a , [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [106]:
a,b,c = np.split(a , [3,5])

In [107]:
a

array([1, 2, 3])

In [108]:
b

array([99, 99])

In [109]:
c

array([3, 2, 1])

## İki Boyutlu Matrislerde Ayırma İşlemi

In [114]:
y = np.arange(16).reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
np.vsplit(y, [2]) # Arrayi tam ortadan satırlara göre bölme işlemine tabii tuttuk

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [117]:
ust,alt = np.split(y,[2])

In [118]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [119]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [121]:
np.hsplit(y,[2]) # Sütünlara göre ayırma işlemini yaptık sütunlara göre tam ortadan böldük

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [124]:
sol,sag = np.hsplit(y, [2])

In [125]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [127]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama İşlemi (Sorting)

In [128]:
import numpy as np

In [151]:
v = np.array([3,7,2,6,9,4,8])
v

array([3, 7, 2, 6, 9, 4, 8])

In [142]:
np.sort(v) # Küçükten Büyüğe Doğru Sıralama İşlemleri 

array([2, 3, 4, 6, 7, 8, 9])

## İki Boytlu Matrisler İçin Sıralama İşlemleri

In [160]:
v = np.random.randint(0, 16, (4,4))
v

array([[ 9, 12, 13, 11],
       [ 4,  0,  3, 15],
       [15,  5, 13,  4],
       [ 3, 11,  3, 10]], dtype=int32)

In [165]:
np.sort(v, axis = 1) # Satır satır küçükren büyüğe sıralama işlemi

array([[ 9, 11, 12, 13],
       [ 0,  3,  4, 15],
       [ 4,  5, 13, 15],
       [ 3,  3, 10, 11]], dtype=int32)

In [166]:
np.sort(v, axis = 0) # Sütun sütun küçükren büyüğe sıralama işlemi 

array([[ 3,  0,  3,  4],
       [ 4,  5,  3, 10],
       [ 9, 11, 13, 11],
       [15, 12, 13, 15]], dtype=int32)

 # İndeks İle Eleman Erişme İşlemi 

In [ ]:
import numpy as np

In [174]:
a = np.random.randint(10 , size = 10)
a

array([2, 3, 6, 6, 7, 9, 2, 3, 8, 2], dtype=int32)

In [177]:
a[0]

np.int32(2)

In [179]:
a[-1]

np.int32(2)

In [181]:
a[0] = 1
a[0]

np.int32(1)

In [186]:
m = np.random.randint(1,10, size = (3,5))
m

array([[9, 6, 1, 5, 2],
       [2, 2, 2, 4, 6],
       [9, 3, 9, 8, 8]], dtype=int32)

In [191]:
m[0][1]

np.int32(6)

In [190]:
m[-1][-3]

np.int32(9)

In [194]:
# 2.Satır 4. elemana erişip değerni değiştirelim
m[1][3]

np.int32(4)

In [196]:
m[1][3] = 5
m[1][3]

np.int32(5)

# Array Alt Küme İşlemleri (Slicing)

In [197]:
import numpy as np

In [198]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [199]:
a[0:3] # sıfırdan indeksten üçüncü indekse kadar git ama üçüncü indeks dahil değil

array([20, 21, 22])

In [200]:
a[:3]

array([20, 21, 22])

In [201]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [202]:
a[1::3] # 1. indeksten den başla 3 er 3 er 

array([21, 24, 27])

In [203]:
a[2::5] # 2.indeksten başla 5 er 5er

array([22, 27])

In [204]:
a[0::1] # 0. indeksten başla 1 er 1 er

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## İki Boyutlu Matrislerde Slicing İşlemleri 

In [208]:
m = np.random.randint(10, size = (5,5))
m

array([[9, 8, 7, 4, 2],
       [1, 5, 0, 4, 8],
       [4, 7, 6, 3, 6],
       [0, 7, 9, 7, 5],
       [9, 1, 5, 5, 1]], dtype=int32)

In [216]:
m[:,0] # virgülden önceki işlem satır işlemlerini ifade eder sonrası ise sütun işlemlerini ifade eder

array([9, 1, 4, 0, 9], dtype=int32)

In [218]:
m[1:,0] # 2.satırdan son satıra kadar  0.sütundaki elemanları göster 

array([1, 4, 0, 9], dtype=int32)

In [220]:
m[0:3, 2] # 0.indeksten 3.indekse kadar ama 3.indeks hariç, 2 indeksteki sütundaki elemları göster

array([7, 0, 6], dtype=int32)

In [222]:
m[1,0:3] #1.indeksteki satırın 0.indeksinden 3. indeksine kadar ama 3. indeks dahil değil

array([1, 5, 0], dtype=int32)

In [223]:
m[1:3,1:3]

array([[5, 0],
       [7, 6]], dtype=int32)

In [225]:
m[1:3,0:2]

array([[1, 5],
       [4, 7]], dtype=int32)

# Alt Küme Üzerinde İşlem Yapmak 

## Matrislerde alt küme işlemlerinde yapcağımız işlemler 
## asıl matriste de değişiklik oluyor bu işlem çok işimize 
## yarasda bazen bunu istemeyiz bunun için alt kümleri bağımsızlaştırma 
## işlemi

In [226]:
import numpy as np
a = np.random.randint(10,size = (5,5))
a

array([[1, 6, 2, 0, 3],
       [4, 4, 6, 9, 0],
       [0, 5, 8, 5, 9],
       [8, 7, 9, 8, 6],
       [7, 7, 9, 1, 2]], dtype=int32)

In [228]:
alt_a = a[0:3,0:2]
alt_a

array([[1, 6],
       [4, 4],
       [0, 5]], dtype=int32)

In [230]:
alt_a[0,0] = 999
alt_a[1,1] = 888
alt_a

array([[999,   6],
       [  4, 888],
       [  0,   5]], dtype=int32)

In [231]:
a

array([[999,   6,   2,   0,   3],
       [  4, 888,   6,   9,   0],
       [  0,   5,   8,   5,   9],
       [  8,   7,   9,   8,   6],
       [  7,   7,   9,   1,   2]], dtype=int32)

## Görüldüğü üzere asıl matristede değişiklik oldu
## Pekii bunun çözümü nedir copy methodudur:


In [233]:
m = np.random.randint(10 , size = (5,5,))
m

array([[0, 9, 7, 5, 4],
       [5, 9, 7, 6, 0],
       [7, 8, 1, 9, 8],
       [0, 4, 4, 9, 0],
       [1, 2, 4, 6, 3]], dtype=int32)

In [235]:
alt_b = m[0:3,0:2].copy() #Bu işlem sonucu ana matristen bağımsız hale gelmiş oldu
alt_b

array([[0, 9],
       [5, 9],
       [7, 8]], dtype=int32)

In [236]:
alt_b[0,0] = 999
alt_b[0,1] = 888
alt_b

array([[999, 888],
       [  5,   9],
       [  7,   8]], dtype=int32)

In [237]:
m

array([[0, 9, 7, 5, 4],
       [5, 9, 7, 6, 0],
       [7, 8, 1, 9, 8],
       [0, 4, 4, 9, 0],
       [1, 2, 4, 6, 3]], dtype=int32)

## Görüldüğü üzere Ana matriste Herhangi Bir Değişme olmadan Değişim yapmış olduk

In [238]:
alt_b*3 # Tüm değerleri 3 ile çarptık

array([[2997, 2664],
       [  15,   27],
       [  21,   24]], dtype=int32)

# **Fancy Index** İle Elemanlara Erişmek (--**ÇOOOK ÖNEMLİ DİKKATLE İNCELE**--)

In [240]:
import numpy as np
v = np.arange(0, 30 , 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
# Bu dizideki 1 3 ve 5 elemanlara erişmek istiyorum

In [241]:
v[1]

np.int64(3)

In [242]:
v[3]

np.int64(9)

In [243]:
v[5]

np.int64(15)

In [244]:
[v[1],v[3],v[5]]

[np.int64(3), np.int64(9), np.int64(15)]

In [245]:
al_getir = [1, 3, 5]

In [246]:
v[al_getir]

array([ 3,  9, 15])

In [ ]:
# Yaptığığmız İşleme Fancy İşlemi Denir 

## İki Boyutta Fancy İşlemi:

In [248]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [250]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [251]:
m[satir,sutun]

array([1, 5])

## Basit İndeks İle Fancy İndeks

In [252]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [254]:
m[1, [1,2]] # 1.indeksli Satırın 1. ve 2. ideksli elemanlarını göster

array([4, 5])

In [258]:
m[0: ,[0,2]] # 0.indeksteki satırından son satıra kadar 0.indeksli sütun ile 2.indeksli sütunun değerlerini göster

array([[0, 2],
       [3, 5],
       [6, 8]])

# Koşullu Eleman İşlemleri 

In [259]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [262]:
v < 3

array([ True,  True, False, False, False])

In [ ]:
# DEğerlere Erişme İşlemi

In [260]:
istenilen_deger = v[v<3]

In [261]:
istenilen_deger

array([1, 2])

# Matematiksel İşlemler 

In [263]:
import numpy as np
v = np.array([1,2,3,4,5])

* v-1
* v*5
* v/5
* v*5/10-2+9
## Bir Dizi İşleme Tabi Tutlabilir

In [ ]:
#ufunc
# +,-,*,/ Gibi işlemlerini kullanıyoruz ama arakda çalışan yapılar bunlar 

In [264]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [265]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [266]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [267]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [268]:
np.mod(v,2)

array([1, 0, 1, 0, 1])

In [276]:
np.absolute(np.array([-3]))        

array([3])

In [277]:
np.sin(360)

np.float64(0.9589157234143065)

In [278]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [279]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

# Numpy İle İki Bilinmeyenli Denklem Çözümü 

In [12]:
import numpy as np

5 * x0 + x1 = 12
x0 + 3 * x1 = 10


In [13]:
a = np.array([[5,1],[3,1]])
b = np.array([[12],[10]])

In [14]:
a

array([[5, 1],
       [3, 1]])

In [15]:
b

array([[12],
       [10]])

In [16]:
x = np.linalg.solve(a,b)
x

array([[1.],
       [7.]])

In [19]:
a = np.array([[4, 0, 3, 0, 1],
       [9, 6, 1, 5, 9],
       [1, 9, 0, 8, 2]])
a

array([[4, 0, 3, 0, 1],
       [9, 6, 1, 5, 9],
       [1, 9, 0, 8, 2]])

In [23]:
a[1,2]

np.int64(1)